Feat/IC-186
luizcdc/portalwepgcomp pull request #194
Opened 2024-12-14 20:15 UTC by Rezende123

2024-12-14 23:39 UTC, ernestosrf approved these changes
Backend ok

2024-12-14 23:39 UTC, jubsribs requested changes
Não entendi pq mexeu no arquivo de backend

2024-12-14 23:39 UTC, jubsribs commented on frontend/src/services/presentation.ts
> +        const instance = axiosInstance();
instance ja foi definido em cima, n precisa aqui

2024-12-14 23:39 UTC, jubsribs commented on frontend/src/services/presentation.ts
> +        const instance = axiosInstance();
instance ja foi definido em cima, n precisa aqui

2024-12-15 14:27 UTC, palomapassos approved these changes

2024-12-16 01:36 UTC, merged