IC-112 - Implementação da funcionalidade de confirmação de email
luizcdc/portalwepgcomp pull request #218
Opened 2024-12-23 01:59 UTC by alvaroxsouza

2024-12-23 20:38 UTC, Kieroth29 requested changes

2024-12-27 12:45 UTC, ernestosrf requested changes
Exceto o que pontuei, o restante parece ok pra mim

2024-12-27 12:45 UTC, ernestosrf commented on backend/.env.example
> +APP_URL=http://localhost:3000
Ja existe uma variável com esse mesmo valor. O "FRONTEND_URL". Recomendo que escolha uma das duas e substitua a outra (mas o mais sensato é manter a que já existia e adaptar a sua implementação)

2024-12-27 14:19 UTC, ernestosrf approved these changes

2024-12-27 14:20 UTC, merged